"""setting a field null

Revision ID: 1a24a8e2cbf5
Revises: bb6d857186e1
Create Date: 2024-04-30 15:24:59.732723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a24a8e2cbf5'
down_revision: Union[str, None] = 'bb6d857186e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
