"""Added friends and notifications

Revision ID: 2a2e10999672
Revises: cafac7afff29
Create Date: 2024-04-08 08:19:48.940005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2e10999672'
down_revision: Union[str, None] = 'cafac7afff29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('following_username', sa.String(), nullable=False),
    sa.Column('date_followed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['following_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username', 'following_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
