"""Added renamed tables

Revision ID: 41f97c1452b2
Revises: 
Create Date: 2024-04-12 11:27:37.691077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f97c1452b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('card',
    sa.Column('card_no', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('card_no', 'username')
    )
    op.create_table('friends',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('following_username', sa.String(), nullable=False),
    sa.Column('date_followed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['following_username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username', 'following_username')
    )
    op.create_table('notification',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username', 'content')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('friends')
    op.drop_table('card')
    op.drop_table('users')
    # ### end Alembic commands ###
