"""added table

Revision ID: 9d512d27db59
Revises: 51cc286e5cf2
Create Date: 2024-04-30 16:03:10.193316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d512d27db59'
down_revision: Union[str, None] = '51cc286e5cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes_table',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('wishes_to', sa.String(), nullable=True),
    sa.Column('wished_by', sa.String(), nullable=True),
    sa.Column('wished_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wished_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['wishes_to'], ['users.username'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.drop_table('wishes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('story_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wishes_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wished_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wished_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['wished_by'], ['users.username'], name='wishes_wished_by_fkey'),
    sa.ForeignKeyConstraint(['wishes_to'], ['users.username'], name='wishes_wishes_to_fkey'),
    sa.PrimaryKeyConstraint('story_id', name='wishes_pkey')
    )
    op.drop_table('wishes_table')
    # ### end Alembic commands ###
