"""Changed time datatypes

Revision ID: ccc705897224
Revises: 3d48790e9777
Create Date: 2024-04-30 15:13:53.006912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc705897224'
down_revision: Union[str, None] = '3d48790e9777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('wishes_to', sa.String(), nullable=True),
    sa.Column('wished_by', sa.String(), nullable=True),
    sa.Column('wished_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wished_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['wishes_to'], ['users.username'], ),
    sa.PrimaryKeyConstraint('story_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    # ### end Alembic commands ###
